# This file was generated by GoReleaser. DO NOT EDIT.
cask "chough" do
  name "chough"
  desc "Fast ASR CLI using Parakeet TDT 0.6b V3"
  homepage "https://github.com/hyperpuncher/chough"
  version "0.1.5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "chough"
  depends_on formula: [
      "ffmpeg",
    ]

  on_macos do
    on_intel do
      url "https://github.com/hyperpuncher/chough/releases/download/v#{version}/chough_v#{version}_darwin_x86_64.tar.gz"
      sha256 "d35ccb0c47618d92f17c099a4ec5fe93cc6d13a0aae372234997f7993135ac7c"
    end
    on_arm do
      url "https://github.com/hyperpuncher/chough/releases/download/v#{version}/chough_v#{version}_darwin_arm64.tar.gz"
      sha256 "455e7883d4e6b590d3417975ecfe8045a2320477ba7fdbc816fa92634d8ae810"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/hyperpuncher/chough/releases/download/v#{version}/chough_v#{version}_linux_x86_64.tar.gz"
      sha256 "a9bc77405578fa07c3671e0c9d5bfb3a395d246a4de78ed5c27087352d43bb46"
    end
  end

  # No zap stanza required
end
